name: Bump version
on:
    push:
        branches:
            - develop
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update package.json with new version
              run: |
                BRANCH_NAME=${GITHUB_REF##*/}
                VERSION=${{ steps.tag_version.outputs.new_version }}
                # If master branch, strip any suffix after a dash
                if [ "$BRANCH_NAME" = "master" ]; then
                  VERSION=$(echo "$VERSION" | cut -d '-' -f1)
                fi
                echo "Updating package.json to version $VERSION"
                jq --arg version "$VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json

            - name: Commit updated package.json
              run: |
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
                git add package.json
                git commit -m "ci: update version to ${{ steps.tag_version.outputs.new_version }}"
                git push origin HEAD
              continue-on-error: true

            - name: Create a GitHub release
              if: github.ref == 'refs/heads/master'
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.tag_version.outputs.new_tag }}
                name: Release ${{ steps.tag_version.outputs.new_tag }}
                body: ${{ steps.tag_version.outputs.changelog }}
